providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.install]
cmds = [
  "npm install -g corepack@0.34.5",
  "corepack enable",
  "corepack prepare pnpm@10.34.4 --activate",
  "pnpm i --frozen-lockfile"
]
